name: speak
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # google_fonts: ^2.3.1
  flutter_screenutil: ^5.6.0
  scribble: ^0.4.0
  grpc: ^3.0.2
  flutter_sound: ^9.2.13
  googleapis: ^9.1.0
  google_sign_in: ^6.1.3
  extension_google_sign_in_as_googleapis_auth: ^2.0.6
  mic_stream: ^0.6.1
  googleapis_auth: ^1.0.0
  http: ^0.13.5
  go_router: ^5.2.1
  firebase_core: ^2.13.1
  hooks_riverpod: ^1.0.4
  firebase_auth: ^4.6.2
  firebase_in_app_messaging: ^0.7.3+2
  cloud_firestore: ^4.8.0
  uuid: ^3.0.7
  image: ^4.0.17
  intl: ^0.18.1
  video_thumbnail: ^0.5.3
  video_player: ^2.6.1
  url_launcher: ^6.1.11
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
