// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVhAWtnnonlaTP95J_2LML2invcC7VTUM',
    appId: '1:581772824821:android:e554b87a0c38d6bcc935bc',
    messagingSenderId: '581772824821',
    projectId: 'speak-388805',
    storageBucket: 'speak-388805.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlslcLxSxcksnpY8-PeK9GiUIIpZuHqGo',
    appId: '1:581772824821:ios:9f7c3f6a54696ecec935bc',
    messagingSenderId: '581772824821',
    projectId: 'speak-388805',
    storageBucket: 'speak-388805.appspot.com',
    androidClientId: '581772824821-r91ofb3glff151357ou4h795s5af0d3q.apps.googleusercontent.com',
    iosClientId: '581772824821-dmsnp2s788psftvpdt0jk9i38hccpb0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.speak',
  );
}
